"""Turn Sam.spd, LTTS1033.LXA and r1033tts.LXA into C arrays (src/sam_data.c) so the
program needs no data files. The generated file contains Microsoft's voice data: personal use only.

usage: python tools/embed_data.py [data/voice]
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILES = [("sam_data_spd", "Sam.spd"), ("sam_data_lex", "LTTS1033.LXA"), ("sam_data_lts", "r1033tts.LXA")]


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "data", "voice")
    out = os.path.join(ROOT, "src", "sam_data.c")
    with open(out, "w", newline="\n") as f:
        f.write("/* Generated by tools/embed_data.py - Microsoft Sam voice data (not for redistribution). */\n")
        f.write('#include "sam_data.h"\n\n')
        for name, fn in FILES:
            d = open(os.path.join(src, fn), "rb").read()
            f.write(f"/* {fn}, {len(d)} bytes */\n")
            f.write(f"const unsigned char {name}[{len(d)}] = {{\n")
            for i in range(0, len(d), 24):
                f.write(",".join(str(b) for b in d[i:i + 24]) + ",\n")
            f.write("};\n")
            f.write(f"const size_t {name}_size = {len(d)};\n\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
